/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.sql.SQLException;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.ListSelectionModel;
import modeloBeans.BeansLivro;
import modeloBeans.ModeloTabela;
import modeloConnection.ConexaoBD;
import modeloDao.DaoLivro;

/**
 *
 * @author Michel
 */
public class FormLivro extends javax.swing.JFrame {

    BeansLivro modLivro = new BeansLivro();
    DaoLivro dao = new DaoLivro();
    ConexaoBD conex = new ConexaoBD(); 
    int flag=0;
    
    public FormLivro() {
        initComponents();
        preencherTabela("select * from livros order by titulo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jButtonNovo = new javax.swing.JButton();
        jButtonSalvar = new javax.swing.JButton();
        jButtonAtualizar = new javax.swing.JButton();
        jButtonDeletar = new javax.swing.JButton();
        jButtonCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTableLivros = new javax.swing.JTable();
        jButtonPesquisar = new javax.swing.JButton();
        jTextFieldPesquisar = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextFieldTitulo = new javax.swing.JTextField();
        jTextFieldAutor = new javax.swing.JTextField();
        jTextFieldGenero = new javax.swing.JTextField();
        jComboBoxDisponibilidade = new javax.swing.JComboBox<>();
        jTextFieldEditora = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldCodigo = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        jTextFieldID = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabelFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel2.setLayout(null);

        jButtonNovo.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonNovo.setText("Novo");
        jButtonNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonNovoActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonNovo);
        jButtonNovo.setBounds(20, 435, 90, 30);

        jButtonSalvar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonSalvar.setText("Salvar");
        jButtonSalvar.setEnabled(false);
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonSalvar);
        jButtonSalvar.setBounds(20, 490, 90, 30);

        jButtonAtualizar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonAtualizar.setText("Atualizar");
        jButtonAtualizar.setEnabled(false);
        jButtonAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAtualizarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonAtualizar);
        jButtonAtualizar.setBounds(20, 540, 90, 30);

        jButtonDeletar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonDeletar.setText("Deletar");
        jButtonDeletar.setEnabled(false);
        jButtonDeletar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeletarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonDeletar);
        jButtonDeletar.setBounds(20, 590, 90, 30);

        jButtonCancelar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonCancelar.setText("Cancelar");
        jButtonCancelar.setEnabled(false);
        jButtonCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCancelarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonCancelar);
        jButtonCancelar.setBounds(20, 635, 90, 30);

        jTableLivros.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jTableLivros.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableLivrosMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTableLivros);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(138, 431, 670, 240);

        jButtonPesquisar.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jButtonPesquisar.setText("Pesquisar");
        jButtonPesquisar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonPesquisarActionPerformed(evt);
            }
        });
        jPanel2.add(jButtonPesquisar);
        jButtonPesquisar.setBounds(139, 380, 90, 30);
        jPanel2.add(jTextFieldPesquisar);
        jTextFieldPesquisar.setBounds(250, 380, 554, 30);

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Disponibiidade:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(20, 247, 91, 20);

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel5.setText("Gênero:");
        jPanel2.add(jLabel5);
        jLabel5.setBounds(30, 210, 49, 17);

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Autor:");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(40, 160, 39, 17);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("Título:");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(40, 107, 38, 20);

        jTextFieldTitulo.setEnabled(false);
        jPanel2.add(jTextFieldTitulo);
        jTextFieldTitulo.setBounds(130, 100, 300, 30);

        jTextFieldAutor.setEnabled(false);
        jPanel2.add(jTextFieldAutor);
        jTextFieldAutor.setBounds(130, 150, 300, 30);

        jTextFieldGenero.setEnabled(false);
        jPanel2.add(jTextFieldGenero);
        jTextFieldGenero.setBounds(130, 200, 300, 30);

        jComboBoxDisponibilidade.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "true", "false" }));
        jComboBoxDisponibilidade.setEnabled(false);
        jPanel2.add(jComboBoxDisponibilidade);
        jComboBoxDisponibilidade.setBounds(130, 240, 300, 30);

        jTextFieldEditora.setEnabled(false);
        jPanel2.add(jTextFieldEditora);
        jTextFieldEditora.setBounds(130, 320, 300, 30);

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Editora:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(30, 317, 48, 30);

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Código:");
        jPanel2.add(jLabel3);
        jLabel3.setBounds(30, 277, 48, 40);

        jTextFieldCodigo.setEnabled(false);
        jPanel2.add(jTextFieldCodigo);
        jTextFieldCodigo.setBounds(130, 280, 300, 30);

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("ID do livro:");
        jPanel2.add(jLabel8);
        jLabel8.setBounds(380, 17, 68, 30);

        jTextFieldID.setEnabled(false);
        jPanel2.add(jTextFieldID);
        jTextFieldID.setBounds(460, 20, 61, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 22)); // NOI18N
        jLabel1.setText("Cadastro de livros");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(60, 20, 200, 40);

        jLabelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoLivro.png"))); // NOI18N
        jPanel2.add(jLabelFundo);
        jLabelFundo.setBounds(0, 0, 990, 700);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, 699, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(1005, 738));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonNovoActionPerformed
        flag = 1;
        jTextFieldTitulo.setEnabled(true);
        jTextFieldCodigo.setEnabled(true);
        jTextFieldAutor.setEnabled(true);
        jTextFieldGenero.setEnabled(true);
        jComboBoxDisponibilidade.setEnabled(true);
        jTextFieldEditora.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        
        jTextFieldTitulo.setText("");
        jTextFieldCodigo.setText("");
        jTextFieldAutor.setText("");
        jTextFieldEditora.setText("");
        jComboBoxDisponibilidade.setSelectedItem("false");
        jButtonAtualizar.setEnabled(false);
        jButtonDeletar.setEnabled(false);
        jButtonPesquisar.setEnabled(false);
        jTextFieldPesquisar.setText("");
        jTextFieldPesquisar.setEnabled(false);
    }//GEN-LAST:event_jButtonNovoActionPerformed

    private void jButtonCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCancelarActionPerformed
            jTextFieldTitulo.setEnabled(!true);
            jTextFieldCodigo.setEnabled(!true);
            jTextFieldAutor.setEnabled(!true);
            jComboBoxDisponibilidade.setEnabled(!true);
            jTextFieldGenero.setEnabled(!true);
            jTextFieldEditora.setEnabled(!true);
            jButtonSalvar.setEnabled(!true);
            jButtonCancelar.setEnabled(!true);
            jButtonNovo.setEnabled(true);
            jButtonAtualizar.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonDeletar.setEnabled(false);
            jTextFieldPesquisar.setText("");
            jTextFieldPesquisar.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
            jTextFieldTitulo.setText("");
            jTextFieldAutor.setText("");
            jTextFieldCodigo.setText("");
            jTextFieldGenero.setText("");
            jTextFieldEditora.setText("");
            jTextFieldID.setText("");
            jComboBoxDisponibilidade.setSelectedItem("false");
    }//GEN-LAST:event_jButtonCancelarActionPerformed

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        if(jTextFieldTitulo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o campo TITULO para continuar");
            jTextFieldTitulo.requestFocus();
        }else if(jTextFieldCodigo.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o campo CÓDIGO para continuar");
            jTextFieldCodigo.requestFocus();
        }else if(jTextFieldEditora.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o campo EDITORA para continuar");
            jTextFieldEditora.requestFocus();
        }else if(jTextFieldGenero.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o campo GÊNERO para continuar");
            jTextFieldGenero.requestFocus();
        }else if(jTextFieldAutor.getText().isEmpty()){
            JOptionPane.showMessageDialog(null,"Preencha o campo AUTOR para continuar");
            jTextFieldAutor.requestFocus();
        }else{

            if(flag == 1){
            modLivro.setTitulo(jTextFieldTitulo.getText());
            modLivro.setAutor(jTextFieldAutor.getText());
            modLivro.setEditora(jTextFieldEditora.getText());
            modLivro.setGenero(jTextFieldGenero.getText());
            modLivro.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
            modLivro.setDisponibilidade(Boolean.parseBoolean((String)jComboBoxDisponibilidade.getSelectedItem()));
            
            
            dao.Salvar(modLivro);

            jTextFieldTitulo.setText("");
            jTextFieldAutor.setText("");
            jTextFieldCodigo.setText("");
            jTextFieldGenero.setText("");
            jTextFieldEditora.setText("");
            

            jTextFieldTitulo.setEnabled(false);
            jTextFieldCodigo.setEnabled(false);
            jTextFieldAutor.setEnabled(false);
            jTextFieldEditora.setEnabled(false);
            jTextFieldGenero.setEnabled(false);
            jComboBoxDisponibilidade.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jTextFieldPesquisar.setText("");
            jTextFieldPesquisar.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
            preencherTabela("select * from livros order by titulo");

            }else{
                modLivro.setTitulo(jTextFieldTitulo.getText());
                modLivro.setAutor(jTextFieldAutor.getText());
                modLivro.setEditora(jTextFieldEditora.getText());
                modLivro.setGenero(jTextFieldGenero.getText());
                modLivro.setCodigo(Integer.parseInt(jTextFieldCodigo.getText()));
                modLivro.setDisponibilidade(Boolean.parseBoolean((String)jComboBoxDisponibilidade.getSelectedItem()));
                modLivro.setId(Integer.parseInt(jTextFieldID.getText()));
                dao.Atualizar(modLivro);

                jTextFieldTitulo.setText("");
                jTextFieldAutor.setText("");
                jTextFieldCodigo.setText("");
                jTextFieldGenero.setText("");
                jTextFieldEditora.setText("");
                
                jTextFieldTitulo.setEnabled(false);
                jTextFieldCodigo.setEnabled(false);
                jTextFieldAutor.setEnabled(false);
                jTextFieldEditora.setEnabled(false);
                jTextFieldGenero.setEnabled(false);
                jComboBoxDisponibilidade.setEnabled(false);
                jButtonSalvar.setEnabled(false);
                jButtonCancelar.setEnabled(false);
                jTextFieldPesquisar.setText("");
                jTextFieldPesquisar.setEnabled(true);
                jButtonPesquisar.setEnabled(true);
                preencherTabela("select * from livros order by titulo");
            }
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jButtonAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAtualizarActionPerformed
        flag = 2;
        jTextFieldTitulo.setEnabled(true);
        jTextFieldCodigo.setEnabled(true);
        jTextFieldAutor.setEnabled(true);
        jComboBoxDisponibilidade.setEnabled(true);
        jTextFieldGenero.setEnabled(true);
        jTextFieldEditora.setEnabled(true);
        jButtonSalvar.setEnabled(true);
        jButtonCancelar.setEnabled(true);
        jButtonAtualizar.setEnabled(false);
        jButtonNovo.setEnabled(false);
        jButtonDeletar.setEnabled(false);
    }//GEN-LAST:event_jButtonAtualizarActionPerformed

    private void jButtonPesquisarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonPesquisarActionPerformed
        modLivro.setPesquisa(jTextFieldPesquisar.getText());
        BeansLivro model = dao.buscaLivro(modLivro);
        if(model.getCodigo()!= 0){
            jTextFieldTitulo.setText(model.getTitulo());
            jTextFieldAutor.setText(model.getAutor());
            jComboBoxDisponibilidade.setSelectedItem(model.isDisponibilidade());
            jTextFieldCodigo.setText(String.valueOf(model.getCodigo()));
            jTextFieldGenero.setText(model.getGenero());
            jTextFieldEditora.setText(model.getEditora());
            jTextFieldID.setText(String.valueOf(model.getId()));

            jButtonAtualizar.setEnabled(true);
            jButtonDeletar.setEnabled(true);
            jButtonCancelar.setEnabled(true);
            jButtonNovo.setEnabled(false);
            preencherTabela("select * from livros where titulo ilike'%"+modLivro.getPesquisa()+"%'");
        }else{
            jButtonAtualizar.setEnabled(false);
            jButtonDeletar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            preencherTabela("select * from livros where titulo ilike'%"+modLivro.getPesquisa()+"%'");
        }
    }//GEN-LAST:event_jButtonPesquisarActionPerformed

    private void jButtonDeletarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeletarActionPerformed
        int resposta = 0;
        resposta = JOptionPane.showConfirmDialog(rootPane,"Deseja realmente excluir!");
        if(resposta == JOptionPane.YES_OPTION){
            modLivro.setId(Integer.parseInt(jTextFieldID.getText()));
            dao.Excluir(modLivro);
            jTextFieldTitulo.setText("");
            jTextFieldAutor.setText("");
            jTextFieldCodigo.setText("");
            jTextFieldGenero.setText("");
            jTextFieldEditora.setText("");
            jTextFieldID.setText("");
            jTextFieldTitulo.setEnabled(false);
            jTextFieldCodigo.setEnabled(false);
            jTextFieldAutor.setEnabled(false);
            jTextFieldEditora.setEnabled(false);
            jTextFieldGenero.setEnabled(false);
            jComboBoxDisponibilidade.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jTextFieldPesquisar.setText("");
            jTextFieldPesquisar.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonAtualizar.setEnabled(false);
            jButtonDeletar.setEnabled(false);
           preencherTabela("select * from livros order by titulo");
        }else{
            jTextFieldTitulo.setText("");
            jTextFieldAutor.setText("");
            jTextFieldCodigo.setText("");
            jTextFieldGenero.setText("");
            jTextFieldEditora.setText("");
            jTextFieldID.setText("");
            jTextFieldTitulo.setEnabled(false);
            jTextFieldCodigo.setEnabled(false);
            jTextFieldAutor.setEnabled(false);
            jTextFieldEditora.setEnabled(false);
            jTextFieldGenero.setEnabled(false);
            jComboBoxDisponibilidade.setEnabled(false);
            jButtonSalvar.setEnabled(false);
            jButtonCancelar.setEnabled(false);
            jTextFieldPesquisar.setText("");
            jTextFieldPesquisar.setEnabled(true);
            jButtonPesquisar.setEnabled(true);
            jButtonSalvar.setEnabled(false);
            jButtonNovo.setEnabled(true);
            jButtonCancelar.setEnabled(false);
            jButtonAtualizar.setEnabled(false);
            jButtonDeletar.setEnabled(false);
        }
    }//GEN-LAST:event_jButtonDeletarActionPerformed

    private void jTableLivrosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableLivrosMouseClicked
        String nome_livro = ""+jTableLivros.getValueAt(jTableLivros.getSelectedRow(),2);
       //JOptionPane.showMessageDialog(null,nome_aluno);
       conex.conexao();
       conex.executeSql("select * from livros where titulo='"+nome_livro+"'");
       try{      
                conex.rs.first();
                jTextFieldID.setText(String.valueOf(conex.rs.getInt("id")));
                jTextFieldTitulo.setText(conex.rs.getString("titulo"));
                jTextFieldAutor.setText(conex.rs.getString("autor"));
                jComboBoxDisponibilidade.setSelectedItem(conex.rs.getString("disponibilidade"));
                jTextFieldGenero.setText(conex.rs.getString("genero"));
                jTextFieldEditora.setText(conex.rs.getString("editora"));
                jTextFieldCodigo.setText(String.valueOf(conex.rs.getInt("codigo")));
       
       }catch(SQLException ex){
           JOptionPane.showMessageDialog(null,"Erro ao selecionar os dados!\nErro: "+ex);
           //Erro: org.postgresql.util.PSQLException:ResultSet não está posicionado corretamente, talvez você precise chamar next.
       }
       
       conex.desconecta();
        jTextFieldTitulo.setEnabled(false);
        jTextFieldCodigo.setEnabled(false);
        jTextFieldAutor.setEnabled(false);
        jTextFieldEditora.setEnabled(false);
        jTextFieldGenero.setEnabled(false);
        jComboBoxDisponibilidade.setEnabled(false);
       jButtonAtualizar.setEnabled(true);
       jButtonDeletar.setEnabled(true);
       jButtonCancelar.setEnabled(true);
       jButtonSalvar.setEnabled(false);
                                     
    }//GEN-LAST:event_jTableLivrosMouseClicked

    public void preencherTabela(String Sql){
    
        ArrayList dados = new ArrayList();
        String [] colunas = new String []{"Id",",Código","Título","Autor","Gênero","Editora","Disponibilidade"};
        conex.conexao();
        conex.executeSql(Sql);
        try{
            conex.rs.first();
            do{
                dados.add(new Object[]{conex.rs.getInt("id"),conex.rs.getInt("codigo"),conex.rs.getString("titulo"),conex.rs.getString("autor"),conex.rs.getString("genero"),conex.rs.getString("editora"),conex.rs.getBoolean("disponibilidade")});
            }while(conex.rs.next());
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,"Busque por outro livro para preencher a tabela!");
        }
        
        ModeloTabela modelo = new ModeloTabela(dados,colunas); 
        
        jTableLivros.setModel(modelo);
        jTableLivros.getColumnModel().getColumn(0).setPreferredWidth(35);
        jTableLivros.getColumnModel().getColumn(0).setResizable(false);
        jTableLivros.getColumnModel().getColumn(1).setPreferredWidth(90);
        jTableLivros.getColumnModel().getColumn(1).setResizable(false);
        jTableLivros.getColumnModel().getColumn(2).setPreferredWidth(200);
        jTableLivros.getColumnModel().getColumn(2).setResizable(false);
        jTableLivros.getColumnModel().getColumn(3).setPreferredWidth(100);
        jTableLivros.getColumnModel().getColumn(3).setResizable(false);
        jTableLivros.getColumnModel().getColumn(4).setPreferredWidth(90);
        jTableLivros.getColumnModel().getColumn(4).setResizable(false);
        jTableLivros.getColumnModel().getColumn(5).setPreferredWidth(167);
        jTableLivros.getColumnModel().getColumn(5).setResizable(false);
        jTableLivros.getColumnModel().getColumn(6).setPreferredWidth(167);
        jTableLivros.getColumnModel().getColumn(6).setResizable(false);
        
        
        jTableLivros.getTableHeader().setReorderingAllowed(false);
        jTableLivros.setAutoResizeMode(jTableLivros.AUTO_RESIZE_OFF);
        jTableLivros.setSelectionMode(ListSelectionModel.SINGLE_SELECTION);
        
        conex.desconecta();
    
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FormLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FormLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FormLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FormLivro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FormLivro().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAtualizar;
    private javax.swing.JButton jButtonCancelar;
    private javax.swing.JButton jButtonDeletar;
    private javax.swing.JButton jButtonNovo;
    private javax.swing.JButton jButtonPesquisar;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JComboBox<String> jComboBoxDisponibilidade;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabelFundo;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTableLivros;
    private javax.swing.JTextField jTextFieldAutor;
    private javax.swing.JTextField jTextFieldCodigo;
    private javax.swing.JTextField jTextFieldEditora;
    private javax.swing.JTextField jTextFieldGenero;
    private javax.swing.JTextField jTextFieldID;
    private javax.swing.JTextField jTextFieldPesquisar;
    private javax.swing.JTextField jTextFieldTitulo;
    // End of variables declaration//GEN-END:variables
}
