/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package visão;

import java.sql.SQLException;
import javax.swing.JOptionPane;
import modeloConnection.ConexaoBD;

/**
 *
 * @author Michel
 */
public class TelaPrincipal extends javax.swing.JFrame {
    
    ConexaoBD conecta = new ConexaoBD();
    FormUsuario telaUsuario = new FormUsuario();
    FormAluno telaAluno = new FormAluno();
    FormLivro telaLivro = new FormLivro();
    FormReserva telaReserva = new FormReserva();
    
    public TelaPrincipal(String usuario) {
        initComponents();
        jLabelUsuario.setText(usuario);
        conecta.conexao();
    }

    private TelaPrincipal() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrameBemVindo = new javax.swing.JInternalFrame();
        jPanelInterno = new javax.swing.JPanel();
        jButtonLivros = new javax.swing.JButton();
        jButtonAlunos = new javax.swing.JButton();
        jButtonProfessores = new javax.swing.JButton();
        jButtonFechar = new javax.swing.JButton();
        jLabelPainelFundo = new javax.swing.JLabel();
        jLabel1Registros = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelUsuario = new javax.swing.JLabel();
        jLabelFundoPrincipal = new javax.swing.JLabel();
        jMenuBarPrincipal = new javax.swing.JMenuBar();
        jMenu1Livros = new javax.swing.JMenu();
        jMenuItemCadLivro = new javax.swing.JMenuItem();
        jMenuItemCadAlunos = new javax.swing.JMenuItem();
        jMenuItemUsuarios = new javax.swing.JMenuItem();
        jMenuItemreservas = new javax.swing.JMenuItem();
        jMenu2Ferramentas = new javax.swing.JMenu();
        jMenuItemBemVindo = new javax.swing.JMenuItem();
        jMenuEncerrar = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jInternalFrameBemVindo.setTitle("Bem-vindo a ABC");
        jInternalFrameBemVindo.setVisible(true);
        jInternalFrameBemVindo.getContentPane().setLayout(null);

        jPanelInterno.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        jPanelInterno.setLayout(null);

        jButtonLivros.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Livro.jpg"))); // NOI18N
        jButtonLivros.setToolTipText("Livros");
        jButtonLivros.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonLivrosActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonLivros);
        jButtonLivros.setBounds(50, 70, 120, 110);

        jButtonAlunos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Alunos.jpg"))); // NOI18N
        jButtonAlunos.setToolTipText("Alunos");
        jButtonAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAlunosActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonAlunos);
        jButtonAlunos.setBounds(210, 70, 120, 110);

        jButtonProfessores.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Professores.jpg"))); // NOI18N
        jButtonProfessores.setToolTipText("Professores");
        jPanelInterno.add(jButtonProfessores);
        jButtonProfessores.setBounds(360, 70, 120, 110);

        jButtonFechar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/Fechar.png"))); // NOI18N
        jButtonFechar.setToolTipText("Fechar Tela Bem-Vindo");
        jButtonFechar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonFecharActionPerformed(evt);
            }
        });
        jPanelInterno.add(jButtonFechar);
        jButtonFechar.setBounds(560, 30, 60, 50);

        jLabelPainelFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoPainel.jpg"))); // NOI18N
        jPanelInterno.add(jLabelPainelFundo);
        jLabelPainelFundo.setBounds(0, 30, 680, 520);

        jLabel1Registros.setFont(new java.awt.Font("Tahoma", 3, 18)); // NOI18N
        jLabel1Registros.setText("Registros:");
        jPanelInterno.add(jLabel1Registros);
        jLabel1Registros.setBounds(10, 0, 120, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Usuário:");
        jPanelInterno.add(jLabel1);
        jLabel1.setBounds(340, 0, 80, 30);

        jLabelUsuario.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanelInterno.add(jLabelUsuario);
        jLabelUsuario.setBounds(420, 0, 260, 30);

        jInternalFrameBemVindo.getContentPane().add(jPanelInterno);
        jPanelInterno.setBounds(10, 0, 680, 560);

        getContentPane().add(jInternalFrameBemVindo);
        jInternalFrameBemVindo.setBounds(60, 60, 710, 600);

        jLabelFundoPrincipal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/FundoPrincipal.png"))); // NOI18N
        getContentPane().add(jLabelFundoPrincipal);
        jLabelFundoPrincipal.setBounds(0, 1, 870, 860);

        jMenu1Livros.setText("Registros");
        jMenu1Livros.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemCadLivro.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemCadLivro.setText("Livros");
        jMenuItemCadLivro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadLivroActionPerformed(evt);
            }
        });
        jMenu1Livros.add(jMenuItemCadLivro);

        jMenuItemCadAlunos.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemCadAlunos.setText("Alunos");
        jMenuItemCadAlunos.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemCadAlunosActionPerformed(evt);
            }
        });
        jMenu1Livros.add(jMenuItemCadAlunos);

        jMenuItemUsuarios.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemUsuarios.setText("Usuários");
        jMenuItemUsuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemUsuariosActionPerformed(evt);
            }
        });
        jMenu1Livros.add(jMenuItemUsuarios);

        jMenuItemreservas.setText("Reservas");
        jMenuItemreservas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemreservasActionPerformed(evt);
            }
        });
        jMenu1Livros.add(jMenuItemreservas);

        jMenuBarPrincipal.add(jMenu1Livros);

        jMenu2Ferramentas.setText("Ferramentas");
        jMenu2Ferramentas.setFocusable(false);
        jMenu2Ferramentas.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jMenuItemBemVindo.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuItemBemVindo.setText("Tela Bem-vindos");
        jMenuItemBemVindo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemBemVindoActionPerformed(evt);
            }
        });
        jMenu2Ferramentas.add(jMenuItemBemVindo);

        jMenuBarPrincipal.add(jMenu2Ferramentas);

        jMenuEncerrar.setText("Encerrar");
        jMenuEncerrar.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jMenuEncerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenuEncerrarMouseClicked(evt);
            }
        });
        jMenuBarPrincipal.add(jMenuEncerrar);

        setJMenuBar(jMenuBarPrincipal);

        setSize(new java.awt.Dimension(881, 920));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItemBemVindoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemBemVindoActionPerformed
       jInternalFrameBemVindo.setVisible(true);
    }//GEN-LAST:event_jMenuItemBemVindoActionPerformed

    private void jMenuItemUsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemUsuariosActionPerformed
        try{
            conecta.executeSql("select * from administradores where nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administradores") || conecta.rs.getString("tipo").equals("Professores")){
                if(telaUsuario == null){
                    telaUsuario = new FormUsuario();
                    telaUsuario.setVisible(true);
                    telaUsuario.setResizable(false);
                }else{
                    telaUsuario.setVisible(true);
                    telaUsuario.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador"+ex);
        }
        
    }//GEN-LAST:event_jMenuItemUsuariosActionPerformed

    private void jButtonFecharActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonFecharActionPerformed
       jInternalFrameBemVindo.dispose();
    }//GEN-LAST:event_jButtonFecharActionPerformed

    private void jMenuItemCadAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadAlunosActionPerformed
        try{
            conecta.executeSql("select * from administradores where nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administradores")|| conecta.rs.getString("tipo").equals("Professores")
                    || conecta.rs.getString("tipo").equals("Alunos")){
                if(telaAluno == null){
                    telaAluno = new FormAluno();
                    telaAluno.setVisible(true);
                    telaAluno.setResizable(false);
                }else{
                    telaAluno.setVisible(true);
                    telaAluno.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador"+ex);
        }
        
        
    }//GEN-LAST:event_jMenuItemCadAlunosActionPerformed

    private void jButtonAlunosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAlunosActionPerformed
         try{
            conecta.executeSql("select * from administradores where nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administradores") || conecta.rs.getString("tipo").equals("Professores")
                    || conecta.rs.getString("tipo").equals("Alunos")){
                if(telaAluno == null){
                    telaAluno = new FormAluno();
                    telaAluno.setVisible(true);
                    telaAluno.setResizable(false);
                }else{
                    telaAluno.setVisible(true);
                    telaAluno.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador"+ex);
        }
    }//GEN-LAST:event_jButtonAlunosActionPerformed

    private void jMenuEncerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenuEncerrarMouseClicked
        conecta.desconecta();
        System.exit(0);
    }//GEN-LAST:event_jMenuEncerrarMouseClicked

    private void jMenuItemCadLivroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemCadLivroActionPerformed
       try{
            conecta.executeSql("select * from administradores where nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administradores")|| conecta.rs.getString("tipo").equals("Professores")
                    || conecta.rs.getString("tipo").equals("Alunos")){
                if(telaLivro == null){
                    telaLivro = new FormLivro();
                    telaLivro.setVisible(true);
                    telaLivro.setResizable(false);
                }else{
                    telaLivro.setVisible(true);
                    telaLivro.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador"+ex);
        }
    }//GEN-LAST:event_jMenuItemCadLivroActionPerformed

    private void jButtonLivrosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonLivrosActionPerformed
        try{
            conecta.executeSql("select * from administradores where nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administradores")|| conecta.rs.getString("tipo").equals("Professores")
                    || conecta.rs.getString("tipo").equals("Alunos")){
                if(telaLivro == null){
                    telaLivro = new FormLivro();
                    telaLivro.setVisible(true);
                    telaLivro.setResizable(false);
                }else{
                    telaLivro.setVisible(true);
                    telaLivro.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador"+ex);
        }
    }//GEN-LAST:event_jButtonLivrosActionPerformed

    private void jMenuItemreservasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemreservasActionPerformed
        try{
            conecta.executeSql("select * from administradores where nome='"+jLabelUsuario.getText()+"'");
            conecta.rs.first();
            if(conecta.rs.getString("tipo").equals("Administradores")|| conecta.rs.getString("tipo").equals("Professores")
                    || conecta.rs.getString("tipo").equals("Alunos")){
                if(telaReserva == null){
                    telaReserva = new FormReserva();
                    telaReserva.setVisible(true);
                    telaReserva.setResizable(false);
                }else{
                    telaReserva.setVisible(true);
                    telaReserva.setResizable(false);
                }
            }else{
                JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador");
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(rootPane,"Você não tem acesso a esta funcionalidade!\n Contate o administrador"+ex);
        }
    }//GEN-LAST:event_jMenuItemreservasActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaPrincipal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAlunos;
    private javax.swing.JButton jButtonFechar;
    private javax.swing.JButton jButtonLivros;
    private javax.swing.JButton jButtonProfessores;
    private javax.swing.JInternalFrame jInternalFrameBemVindo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel1Registros;
    private javax.swing.JLabel jLabelFundoPrincipal;
    private javax.swing.JLabel jLabelPainelFundo;
    private javax.swing.JLabel jLabelUsuario;
    private javax.swing.JMenu jMenu1Livros;
    private javax.swing.JMenu jMenu2Ferramentas;
    private javax.swing.JMenuBar jMenuBarPrincipal;
    private javax.swing.JMenu jMenuEncerrar;
    private javax.swing.JMenuItem jMenuItemBemVindo;
    private javax.swing.JMenuItem jMenuItemCadAlunos;
    private javax.swing.JMenuItem jMenuItemCadLivro;
    private javax.swing.JMenuItem jMenuItemUsuarios;
    private javax.swing.JMenuItem jMenuItemreservas;
    private javax.swing.JPanel jPanelInterno;
    // End of variables declaration//GEN-END:variables
}
